import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:http/http.dart' as http;

class MovieAiSuggestion {
  final String title;
  final String description;
  final String? coverImageUrl;

  const MovieAiSuggestion({
    required this.title,
    required this.description,
    required this.coverImageUrl,
  });
}

class MovieAiException implements Exception {
  final String message;
  final int? statusCode;

  const MovieAiException(this.message, {this.statusCode});

  @override
  String toString() {
    if (statusCode == null) return message;
    return 'HTTP $statusCode: $message';
  }
}

class MovieAiService {
  MovieAiService({
    String apiKey = const String.fromEnvironment('GEMINI_API_KEY'),
    String model = 'gemini-2.5-flash',
    http.Client? client,
  })  : _apiKey = apiKey.trim(),
        _model = model.trim().isEmpty ? 'gemini-2.5-flash' : model.trim(),
        _client = client ?? http.Client();

  final String _apiKey;
  final String _model;
  final http.Client _client;

  Future<MovieAiSuggestion> detectMovieFromImage({
    required Uint8List imageBytes,
    required String mimeType,
  }) async {
    if (_apiKey.isEmpty) {
      throw const MovieAiException(
        'Gemini API key is missing. Set --dart-define=GEMINI_API_KEY=...',
      );
    }
    if (imageBytes.isEmpty) {
      throw const MovieAiException('Image is empty');
    }

    final uri = Uri.parse(
      'https://generativelanguage.googleapis.com/v1beta/models/$_model:generateContent?key=$_apiKey',
    );

    const prompt = '''
Identify the movie shown in this image (poster, screenshot, or scene).
Return only JSON object with this exact schema:
{
  "title": "string",
  "description": "string",
  "image_url": "string"
}

Rules:
- title: official movie title, max 120 chars.
- description: concise plot summary, max 400 chars.
- image_url: direct online image URL (http/https) for movie poster/cover.
- If unsure, make best effort guess from visual cues.
- Do not add markdown, explanations, or any extra keys.
''';

    final payload = <String, dynamic>{
      'contents': [
        {
          'parts': [
            {'text': prompt},
            {
              'inlineData': {
                'mimeType': mimeType,
                'data': base64Encode(imageBytes),
              },
            },
          ],
        },
      ],
      'generationConfig': {
        'temperature': 0.2,
        'responseMimeType': 'application/json',
      },
    };

    late final http.Response response;
    try {
      response = await _client
          .post(
            uri,
            headers: const {
              'Content-Type': 'application/json',
            },
            body: jsonEncode(payload),
          )
          .timeout(const Duration(seconds: 45));
    } on TimeoutException {
      throw const MovieAiException('Gemini request timed out');
    }

    final responseText = utf8.decode(response.bodyBytes);
    dynamic decoded;
    try {
      decoded = jsonDecode(responseText);
    } catch (_) {
      throw MovieAiException(
        responseText.isEmpty ? 'Gemini returned invalid JSON' : responseText,
        statusCode: response.statusCode,
      );
    }

    final responseMap = _readMap(decoded);
    if (responseMap == null) {
      throw const MovieAiException('Unexpected Gemini response format');
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      final message = _readErrorMessage(responseMap) ?? 'Gemini request failed';
      throw MovieAiException(message, statusCode: response.statusCode);
    }

    final text = _extractTextResponse(responseMap);
    if (text.trim().isEmpty) {
      throw const MovieAiException('Gemini response did not contain text');
    }

    final aiMap = _extractJsonObject(text);
    final title = _normalizeText(aiMap['title'], max: 120);
    final description = _normalizeText(aiMap['description'], max: 2000);
    final imageUrlRaw = _normalizeText(
      aiMap['image_url'] ?? aiMap['imageUrl'] ?? aiMap['cover_image'],
      max: 2048,
    );

    if (title.isEmpty) {
      throw const MovieAiException('Failed to detect movie title');
    }

    final normalizedDescription = description.isEmpty
        ? 'Description generated by AI is not available. Please edit.'
        : description;

    final coverImageUrl = _normalizeHttpUrl(imageUrlRaw);

    return MovieAiSuggestion(
      title: title,
      description: normalizedDescription,
      coverImageUrl: coverImageUrl,
    );
  }

  void dispose() {
    _client.close();
  }
}

Map<String, dynamic>? _readMap(Object? value) {
  if (value is! Map) return null;
  return value.map(
    (key, item) => MapEntry(key.toString(), item),
  );
}

String? _readErrorMessage(Map<String, dynamic> responseMap) {
  final errorMap = _readMap(responseMap['error']);
  if (errorMap == null) return null;
  final message = errorMap['message']?.toString().trim() ?? '';
  return message.isEmpty ? null : message;
}

String _extractTextResponse(Map<String, dynamic> responseMap) {
  final candidates = responseMap['candidates'];
  if (candidates is! List || candidates.isEmpty) return '';

  final candidateMap = _readMap(candidates.first);
  final contentMap =
      candidateMap == null ? null : _readMap(candidateMap['content']);
  final parts = contentMap == null ? null : contentMap['parts'];
  if (parts is! List || parts.isEmpty) return '';

  final buffer = StringBuffer();
  for (final part in parts) {
    final partMap = _readMap(part);
    final text = partMap?['text']?.toString() ?? '';
    if (text.trim().isEmpty) continue;
    if (buffer.isNotEmpty) buffer.writeln();
    buffer.write(text);
  }

  return buffer.toString();
}

Map<String, dynamic> _extractJsonObject(String rawText) {
  var text = rawText.trim();

  if (text.startsWith('```')) {
    text = text.replaceFirst(
      RegExp(r'^```(?:json)?\s*', caseSensitive: false),
      '',
    );
    text = text.replaceFirst(RegExp(r'\s*```$'), '');
    text = text.trim();
  }

  final firstBrace = text.indexOf('{');
  final lastBrace = text.lastIndexOf('}');
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    text = text.substring(firstBrace, lastBrace + 1);
  }

  final decoded = jsonDecode(text);
  final map = _readMap(decoded);
  if (map == null) {
    throw const MovieAiException('Gemini result is not a JSON object');
  }
  return map;
}

String _normalizeText(Object? value, {required int max}) {
  final text = value?.toString().trim() ?? '';
  if (text.isEmpty) return '';
  if (text.length <= max) return text;
  return text.substring(0, max).trim();
}

String? _normalizeHttpUrl(String value) {
  final trimmed = value.trim();
  if (trimmed.isEmpty) return null;

  var normalized = trimmed;
  if (normalized.startsWith('//')) {
    normalized = 'https:$normalized';
  }

  final uri = Uri.tryParse(normalized);
  if (uri == null) return null;
  final scheme = uri.scheme.toLowerCase();
  if (scheme != 'http' && scheme != 'https') return null;
  return normalized;
}
