import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:http/http.dart' as http;

class MovieAiSuggestion {
  final String title;
  final String description;
  final String? movieUrl;
  final String? coverImageUrl;

  const MovieAiSuggestion({
    required this.title,
    required this.description,
    required this.movieUrl,
    required this.coverImageUrl,
  });
}

class MovieAiException implements Exception {
  final String message;
  final int? statusCode;

  const MovieAiException(this.message, {this.statusCode});

  @override
  String toString() {
    if (statusCode == null) return message;
    return 'HTTP $statusCode: $message';
  }
}

class MovieAiService {
  MovieAiService({
    String apiKey = const String.fromEnvironment('GEMINI_API_KEY'),
    String model = 'gemini-2.5-flash-preview',
    http.Client? client,
  })  : _apiKey = apiKey.trim(),
        _model =
            model.trim().isEmpty ? 'gemini-2.5-flash-preview' : model.trim(),
        _client = client ?? http.Client();

  final String _apiKey;
  final String _model;
  final http.Client _client;
  static const String _blockedImageHost = 'm.media-amazon.com';

  Future<MovieAiSuggestion> detectMovieFromImage({
    required Uint8List imageBytes,
    required String mimeType,
  }) async {
    if (_apiKey.isEmpty) {
      throw const MovieAiException(
        'Gemini API key is missing. Set --dart-define=GEMINI_API_KEY=...',
      );
    }
    if (imageBytes.isEmpty) {
      throw const MovieAiException('Image is empty');
    }

    final uri = Uri.parse(
      'https://generativelanguage.googleapis.com/v1beta/models/$_model:generateContent?key=$_apiKey',
    );

    const prompt = '''
Identify the movie shown in this image (poster, screenshot, or scene).
Return only JSON object with this exact schema:
{
  "title": "string",
  "description": "string",
  "movie_url": "string",
  "image_url": "string"
}

Rules:
- title: official movie title, max 120 chars.
- description: concise plot summary, max 400 chars.
- movie_url: official webpage URL for this movie (http/https).
- image_url: direct online image URL (http/https) for movie poster/cover.
- If unsure, make best effort guess from visual cues.
- Do not add markdown, explanations, or any extra keys.
''';

    final payload = <String, dynamic>{
      'contents': [
        {
          'parts': [
            {'text': prompt},
            {
              'inlineData': {
                'mimeType': mimeType,
                'data': base64Encode(imageBytes),
              },
            },
          ],
        },
      ],
      'generationConfig': {
        'temperature': 0.2,
        'responseMimeType': 'application/json',
      },
    };

    late final http.Response response;
    try {
      response = await _client
          .post(
            uri,
            headers: const {
              'Content-Type': 'application/json',
            },
            body: jsonEncode(payload),
          )
          .timeout(const Duration(seconds: 45));
    } on TimeoutException {
      throw const MovieAiException('Gemini request timed out');
    }

    final responseText = utf8.decode(response.bodyBytes);
    dynamic decoded;
    try {
      decoded = jsonDecode(responseText);
    } catch (_) {
      throw MovieAiException(
        responseText.isEmpty ? 'Gemini returned invalid JSON' : responseText,
        statusCode: response.statusCode,
      );
    }

    final responseMap = _readMap(decoded);
    if (responseMap == null) {
      throw const MovieAiException('Unexpected Gemini response format');
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      final message = _readErrorMessage(responseMap) ?? 'Gemini request failed';
      throw MovieAiException(message, statusCode: response.statusCode);
    }

    final text = _extractTextResponse(responseMap);
    if (text.trim().isEmpty) {
      throw const MovieAiException('Gemini response did not contain text');
    }

    final aiMap = _extractJsonObject(text);
    final title = _normalizeText(aiMap['title'], max: 120);
    final description = _normalizeText(aiMap['description'], max: 2000);
    final movieUrlRaw = _normalizeText(
      aiMap['movie_url'] ?? aiMap['movieUrl'] ?? aiMap['url'],
      max: 2048,
    );
    final imageUrlRaw = _normalizeText(
      aiMap['image_url'] ?? aiMap['imageUrl'] ?? aiMap['cover_image'],
      max: 2048,
    );

    if (title.isEmpty) {
      throw const MovieAiException('Failed to detect movie title');
    }

    final normalizedDescription = description.isEmpty
        ? 'Description generated by AI is not available. Please edit.'
        : description;

    final itunesMetadata = await _fetchItunesMetadata(title);
    final googleImageUrl = await _fetchGoogleImageUrl(title);
    final movieUrl = await _pickFirstValidMovieUrl(
      candidates: [
        itunesMetadata?.movieUrl,
        movieUrlRaw,
      ],
    );
    final coverImageUrl = await _pickFirstValidImageUrl(
      candidates: [
        googleImageUrl,
        itunesMetadata?.coverImageUrl,
        imageUrlRaw,
      ],
    );

    return MovieAiSuggestion(
      title: title,
      description: normalizedDescription,
      movieUrl: movieUrl,
      coverImageUrl: coverImageUrl,
    );
  }

  void dispose() {
    _client.close();
  }

  Future<_ItunesMovieMetadata?> _fetchItunesMetadata(String title) async {
    final normalizedTitle = title.trim();
    if (normalizedTitle.isEmpty) return null;

    final uri = Uri.https('itunes.apple.com', '/search', {
      'media': 'movie',
      'entity': 'movie',
      'limit': '8',
      'term': normalizedTitle,
    });

    http.Response response;
    try {
      response = await _client.get(uri).timeout(const Duration(seconds: 12));
    } on TimeoutException {
      return null;
    } catch (_) {
      return null;
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      return null;
    }

    final decoded = jsonDecode(utf8.decode(response.bodyBytes));
    final responseMap = _readMap(decoded);
    if (responseMap == null) return null;

    final results = responseMap['results'];
    if (results is! List || results.isEmpty) return null;

    Map<String, dynamic>? best;
    var bestScore = -1;
    final expected = _normalizeComparable(title);

    for (final item in results) {
      final map = _readMap(item);
      if (map == null) continue;

      final candidateTitle = _normalizeComparable(
        map['trackName']?.toString() ?? '',
      );
      var score = 0;
      if (candidateTitle == expected && expected.isNotEmpty) {
        score += 10;
      } else if (candidateTitle.contains(expected) && expected.isNotEmpty) {
        score += 5;
      } else if (expected.contains(candidateTitle) &&
          candidateTitle.isNotEmpty) {
        score += 3;
      }

      final hasImage =
          (map['artworkUrl100']?.toString().trim().isNotEmpty ?? false) ||
              (map['artworkUrl60']?.toString().trim().isNotEmpty ?? false);
      final hasUrl =
          (map['trackViewUrl']?.toString().trim().isNotEmpty ?? false) ||
              (map['collectionViewUrl']?.toString().trim().isNotEmpty ?? false);
      if (hasImage) score += 1;
      if (hasUrl) score += 1;

      if (score > bestScore) {
        bestScore = score;
        best = map;
      }
    }

    if (best == null) return null;

    final movieUrl = _normalizeHttpUrl(
      best['trackViewUrl']?.toString() ?? best['collectionViewUrl']?.toString(),
    );
    final coverImageUrl = _normalizeHttpUrl(
      best['artworkUrl100']?.toString() ?? best['artworkUrl60']?.toString(),
    );

    return _ItunesMovieMetadata(
      movieUrl: movieUrl,
      coverImageUrl: _upgradeItunesArtwork(coverImageUrl),
    );
  }

  Future<String?> _pickFirstValidMovieUrl({
    required List<String?> candidates,
  }) async {
    for (final candidate in candidates) {
      final normalized = _normalizeHttpUrl(candidate);
      if (normalized == null) continue;
      if (await _isReachable(normalized)) {
        return normalized;
      }
    }
    return null;
  }

  Future<String?> _pickFirstValidImageUrl({
    required List<String?> candidates,
  }) async {
    for (final candidate in candidates) {
      final normalized = _normalizeHttpUrl(candidate);
      if (normalized == null) continue;
      if (_isBlockedImageHost(normalized)) continue;
      if (await _isImageUrl(normalized)) {
        return normalized;
      }
    }
    return null;
  }

  Future<String?> _fetchGoogleImageUrl(String title) async {
    final query = title.trim();
    if (query.isEmpty) return null;

    final uri = Uri.https('www.google.com', '/search', {
      'tbm': 'isch',
      'hl': 'en',
      'q': '$query movie poster',
      'safe': 'active',
    });

    http.Response response;
    try {
      response = await _client.get(
        uri,
        headers: const {
          'User-Agent':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
          'Accept-Language': 'en-US,en;q=0.9',
        },
      ).timeout(const Duration(seconds: 12));
    } on TimeoutException {
      return null;
    } catch (_) {
      return null;
    }

    if (response.statusCode < 200 || response.statusCode >= 300) {
      return null;
    }

    final html = utf8.decode(response.bodyBytes);
    final candidates = _extractGoogleImageCandidates(html);

    for (final candidate in candidates) {
      final normalized = _normalizeHttpUrl(candidate);
      if (normalized == null) continue;
      if (_isBlockedImageHost(normalized)) continue;
      if (await _isImageUrl(normalized)) {
        return normalized;
      }
    }
    return null;
  }

  Future<bool> _isReachable(String url) async {
    final uri = Uri.tryParse(url);
    if (uri == null) return false;

    try {
      final response =
          await _client.head(uri).timeout(const Duration(seconds: 8));
      if (response.statusCode >= 200 && response.statusCode < 400) {
        return true;
      }
    } catch (_) {
      // Fallback below.
    }

    try {
      final response = await _client.get(uri, headers: const {
        'Range': 'bytes=0-256'
      }).timeout(const Duration(seconds: 8));
      return response.statusCode >= 200 && response.statusCode < 400;
    } catch (_) {
      return false;
    }
  }

  Future<bool> _isImageUrl(String url) async {
    final uri = Uri.tryParse(url);
    if (uri == null) return false;

    final ext = uri.path.toLowerCase();
    if (ext.endsWith('.jpg') ||
        ext.endsWith('.jpeg') ||
        ext.endsWith('.png') ||
        ext.endsWith('.webp') ||
        ext.endsWith('.gif') ||
        ext.endsWith('.bmp') ||
        ext.endsWith('.avif')) {
      return true;
    }

    try {
      final response =
          await _client.head(uri).timeout(const Duration(seconds: 8));
      final contentType = response.headers['content-type']?.toLowerCase() ?? '';
      if (response.statusCode >= 200 &&
          response.statusCode < 400 &&
          contentType.startsWith('image/')) {
        return true;
      }
    } catch (_) {
      // Fallback below.
    }

    try {
      final response = await _client.get(uri, headers: const {
        'Range': 'bytes=0-1024'
      }).timeout(const Duration(seconds: 8));
      final contentType = response.headers['content-type']?.toLowerCase() ?? '';
      return response.statusCode >= 200 &&
          response.statusCode < 400 &&
          contentType.startsWith('image/');
    } catch (_) {
      return false;
    }
  }

  List<String> _extractGoogleImageCandidates(String html) {
    if (html.trim().isEmpty) return const <String>[];

    final cleaned = html
        .replaceAll(r'\/', '/')
        .replaceAll(r'\u003d', '=')
        .replaceAll(r'\u0026', '&')
        .replaceAll(r'\\u003d', '=')
        .replaceAll(r'\\u0026', '&');

    final matches = RegExp(
      r'''https?:\/\/[^\s"'<>]+''',
      caseSensitive: false,
    ).allMatches(cleaned);

    final result = <String>[];
    final seen = <String>{};

    for (final match in matches) {
      final raw = match.group(0);
      if (raw == null || raw.trim().isEmpty) continue;

      final normalized = _normalizeHttpUrl(raw);
      if (normalized == null) continue;
      if (!_looksLikeImageCandidate(normalized)) continue;
      if (_isBlockedImageHost(normalized)) continue;

      if (seen.add(normalized)) {
        result.add(normalized);
      }
      if (result.length >= 20) break;
    }

    return List<String>.unmodifiable(result);
  }

  bool _looksLikeImageCandidate(String url) {
    final uri = Uri.tryParse(url);
    if (uri == null) return false;

    final host = uri.host.toLowerCase();
    if (host.contains('gstatic.com') ||
        host.contains('googleusercontent.com') ||
        host.contains('ggpht.com')) {
      return true;
    }

    final path = uri.path.toLowerCase();
    return path.endsWith('.jpg') ||
        path.endsWith('.jpeg') ||
        path.endsWith('.png') ||
        path.endsWith('.webp') ||
        path.endsWith('.gif') ||
        path.endsWith('.bmp') ||
        path.endsWith('.avif');
  }

  bool _isBlockedImageHost(String url) {
    final uri = Uri.tryParse(url);
    if (uri == null) return false;
    return uri.host.toLowerCase() == _blockedImageHost;
  }
}

Map<String, dynamic>? _readMap(Object? value) {
  if (value is! Map) return null;
  return value.map(
    (key, item) => MapEntry(key.toString(), item),
  );
}

String? _readErrorMessage(Map<String, dynamic> responseMap) {
  final errorMap = _readMap(responseMap['error']);
  if (errorMap == null) return null;
  final message = errorMap['message']?.toString().trim() ?? '';
  return message.isEmpty ? null : message;
}

String _extractTextResponse(Map<String, dynamic> responseMap) {
  final candidates = responseMap['candidates'];
  if (candidates is! List || candidates.isEmpty) return '';

  final candidateMap = _readMap(candidates.first);
  final contentMap =
      candidateMap == null ? null : _readMap(candidateMap['content']);
  final parts = contentMap == null ? null : contentMap['parts'];
  if (parts is! List || parts.isEmpty) return '';

  final buffer = StringBuffer();
  for (final part in parts) {
    final partMap = _readMap(part);
    final text = partMap?['text']?.toString() ?? '';
    if (text.trim().isEmpty) continue;
    if (buffer.isNotEmpty) buffer.writeln();
    buffer.write(text);
  }

  return buffer.toString();
}

Map<String, dynamic> _extractJsonObject(String rawText) {
  var text = rawText.trim();

  if (text.startsWith('```')) {
    text = text.replaceFirst(
      RegExp(r'^```(?:json)?\s*', caseSensitive: false),
      '',
    );
    text = text.replaceFirst(RegExp(r'\s*```$'), '');
    text = text.trim();
  }

  final firstBrace = text.indexOf('{');
  final lastBrace = text.lastIndexOf('}');
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    text = text.substring(firstBrace, lastBrace + 1);
  }

  final decoded = jsonDecode(text);
  final map = _readMap(decoded);
  if (map == null) {
    throw const MovieAiException('Gemini result is not a JSON object');
  }
  return map;
}

String _normalizeText(Object? value, {required int max}) {
  final text = value?.toString().trim() ?? '';
  if (text.isEmpty) return '';
  if (text.length <= max) return text;
  return text.substring(0, max).trim();
}

String? _normalizeHttpUrl(String? value) {
  var trimmed = (value ?? '').trim();
  if (trimmed.isEmpty) return null;

  trimmed = _extractUrlFromHtmlLike(trimmed)
      .replaceAll(r'\/', '/')
      .replaceAll('&amp;', '&')
      .replaceAll('\n', '')
      .replaceAll('\r', '')
      .trim();

  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) ||
      (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    trimmed = trimmed.substring(1, trimmed.length - 1).trim();
  }

  var normalized = trimmed;
  if (normalized.startsWith('//')) {
    normalized = 'https:$normalized';
  } else if (normalized.startsWith('www.')) {
    normalized = 'https://$normalized';
  } else if (!normalized.startsWith('http://') &&
      !normalized.startsWith('https://')) {
    final domainLike = RegExp(r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}(/.*)?$');
    if (domainLike.hasMatch(normalized)) {
      normalized = 'https://$normalized';
    }
  }

  final uri = Uri.tryParse(normalized);
  if (uri == null) return null;

  final wrapped = _extractWrappedUrl(uri);
  if (wrapped != null) {
    final unwrapped = _normalizeHttpUrl(wrapped);
    if (unwrapped != null) return unwrapped;
  }

  final scheme = uri.scheme.toLowerCase();
  if (scheme != 'http' && scheme != 'https') return null;
  if (scheme == 'http') {
    return uri.replace(scheme: 'https').toString();
  }
  return uri.toString();
}

String _extractUrlFromHtmlLike(String value) {
  final sourceAttrPattern = RegExp(
    r'''(?:src|href)\s*=\s*["']([^"']+)["']''',
    caseSensitive: false,
  );
  final sourceAttrMatch = sourceAttrPattern.firstMatch(value);
  if (sourceAttrMatch != null) {
    return sourceAttrMatch.group(1)?.trim() ?? value;
  }

  final plainUrlPattern = RegExp(
    r'''https?:\/\/[^\s"'<>]+''',
    caseSensitive: false,
  );
  final plainUrlMatch = plainUrlPattern.firstMatch(value);
  if (plainUrlMatch != null) {
    return plainUrlMatch.group(0)?.trim() ?? value;
  }

  return value;
}

String _normalizeComparable(String value) {
  return value.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '');
}

String? _extractWrappedUrl(Uri uri) {
  for (final key in const ['imgurl', 'url', 'mediaurl', 'u']) {
    final raw = uri.queryParameters[key]?.trim();
    if (raw == null || raw.isEmpty) continue;
    final decoded = Uri.decodeFull(raw);
    if (decoded.startsWith('http://') || decoded.startsWith('https://')) {
      return decoded;
    }
  }
  return null;
}

String? _upgradeItunesArtwork(String? url) {
  if (url == null || url.isEmpty) return url;
  return url.replaceAll(RegExp(r'\d+x\d+bb'), '600x600bb');
}

class _ItunesMovieMetadata {
  final String? movieUrl;
  final String? coverImageUrl;

  const _ItunesMovieMetadata({
    required this.movieUrl,
    required this.coverImageUrl,
  });
}
